Fix two compiler warnings
Fix this:

    /home/smarchi/src/libtap-prev/libtap/src/tap.c: In function ‘_gen_result’:
    /home/smarchi/src/libtap-prev/libtap/src/tap.c:87:7: error: implicit declaration of function ‘vasprintf’; did you mean ‘vsprintf’? [-Werror=implicit-function-declaration]
       if (vasprintf(&local_test_name, test_name, ap) < 0)
           ^~~~~~~~~
           vsprintf

by defining the GNU_SOURCE macro, as described in vasprintf's man page.

Fix this:

    /home/smarchi/src/libtap-prev/libtap/src/tap.h:41:12: error: ‘plan’ defined but not used [-Werror=unused-function]
     static int plan(unsigned int tests)
                ^~~~

by marking the function inline.  At least for gcc, adding "inline" makes
it not warn about unused static functions in header files.